version: 2
mkdocs:
  configuration: mkdocs.yml  # Specify the path to the MkDocs configuration file
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# the build.os and build.tools section is mandatory
build:
  os: ubuntu-20.04  # for consistency, matches the one used for CI
  tools:
    python: "3.10"