# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_reproj.ipynb (unless otherwise specified).

__all__ = []

# Cell
import pandas as pd
import xarray as xr
import numpy as np
import numpy.ma as ma

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import colors
import seaborn as sns

import os
import time
from itertools import product
from collections import OrderedDict
from datetime import datetime
from ipypb import track
import FEAutils as hlp

import satpy
from satpy import Scene
from pyresample.geometry import AreaDefinition
import geopandas as gpd
from shapely.geometry import Point
import cartopy.crs as ccrs
import pyinterp
import pyinterp.backends.xarray

import rasterio
from rasterio import Affine as A
from rasterio.warp import reproject, Resampling, calculate_default_transform, transform
from rasterio.control import GroundControlPoint
from rasterio.transform import xy